[package]
name = "Auction-House"
version = "0.0.1"
authors = ["Manish Shankla"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"